spring:
  application:
    name: keycloak-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/customer-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client.service-url:
    defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
